[package]
name = "bevy_animation_derive"
version = "0.3.0"
authors = ["Felipe Jorge <felipe.jorge.pereira@gmail.com>"]
edition = "2018"
description = "Derive implementations for bevy_animation"
license = "MIT"
keywords = ["bevy"]

[lib]
proc-macro = true

[dependencies]
find-crate = "0.6"
syn = "1.0"
proc-macro2 = "1.0"
quote = "1.0"